services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "php artisan migrate --force || true; php -d opcache.enable=0 -d opcache.enable_cli=0 -d opcache.jit_buffer_size=0 -S 0.0.0.0:8000 -t public"

  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ~/.npm:/root/.npm
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
